'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [toggleValue, setToggleValue] = useState(true)
    const handleToggleValue = (toggle) => {
        setToggleValue(toggle)
    }
  return (
    <html lang="en">
      <body className={inter.className}>
        
          {children}
      </body>
    </html>
  );
}
