'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [toggleValue, setToggleValue] = useState(false)
    const handleToggleValue = (toggle) => {
        setToggleValue(toggle)
    }
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex ">
          <div className="min-w-[50px] w-[300px] max-w-[300px]">
            <Sidebar toggleValue={toggleValue} />
          </div>
          <main className="flex-1">
            <Header handleToggleValue={handleToggleValue}/>
            {children}
            <Footer />
          </main>
        </div>
      </body>
    </html>
  );
}
